import { defineAsyncComponent } from 'vue';

export const EDITOR_REGISTRY: Record<string, any> = {
    // Beta — bloques portados de los componentes de webunificada.
    EventsFeatured: defineAsyncComponent(() => import('../components/block-beta/events/events-featured/Editor.vue')),
    PostsFeatured: defineAsyncComponent(() => import('../components/block-beta/events/posts-featured/Editor.vue')),
    CtaBandImage: defineAsyncComponent(() => import('../components/block-beta/cta/ctaband-image/Editor.vue')),
    CtaBandFullImage: defineAsyncComponent(() => import('../components/block-beta/cta/ctaband-full-image/Editor.vue')),
    CtaBandSolid: defineAsyncComponent(() => import('../components/block-beta/cta/ctaband-solid/Editor.vue')),
    CtaBandCompact: defineAsyncComponent(() => import('../components/block-beta/cta/ctaband-compact/Editor.vue')),

    NuestroRepositorio: defineAsyncComponent(() => import('../components/blocks/contenido/nuestro-repositorio/Editor.vue')),
    FooterSimple: defineAsyncComponent(() => import('../components/blocks/footer/footer-simple/Editor.vue')),
    HeaderDynamic: defineAsyncComponent(() => import('../components/blocks/header/header-dynamic/Editor.vue')),
    LeadFormHero: defineAsyncComponent(() => import('../components/blocks/form/lead-form-hero/Editor.vue')),
    TestimonialSlider: defineAsyncComponent(() => import('../components/blocks/testimonios/testimonial-slider/Editor.vue')),
    HeroCollage: defineAsyncComponent(() => import('../components/blocks/hero/hero-collage/Editor.vue')),
    HeroDefault: defineAsyncComponent(() => import('../components/blocks/hero/hero-default/Editor.vue')),
    StatsGrid: defineAsyncComponent(() => import('../components/blocks/grillas/stats-grid/Editor.vue')),
    CtaBanner: defineAsyncComponent(() => import('../components/blocks/conversion/cta-banner/Editor.vue')),
    QuienesSomos: defineAsyncComponent(() => import('../components/blocks/institucional/quienes-somos/Editor.vue')),
    MisionVision: defineAsyncComponent(() => import('../components/blocks/institucional/mision-vision/Editor.vue')),
    NuestrosObjetivos: defineAsyncComponent(() => import('../components/blocks/institucional/nuestros-objetivos/Editor.vue')),
    NuestrosObjetivos2: defineAsyncComponent(() => import('../components/blocks/institucional/nuestros-objetivos2/Editor.vue')),
    Lineamientos: defineAsyncComponent(() => import('../components/blocks/institucional/lineamientos/Editor.vue')),
    AliadosSlider: defineAsyncComponent(() => import('../components/blocks/institucional/aliados-slider/Editor.vue')),
    EventosNoticias: defineAsyncComponent(() => import('../components/blocks/grillas/eventos-noticias/Editor.vue')),
    FasesProceso: defineAsyncComponent(() => import('../components/blocks/grillas/fases-proceso/Editor.vue')),
    DirectorioRectores: defineAsyncComponent(() => import('../components/blocks/grillas/directorio-rectores/Editor.vue')),
    EstructuraOrganizacional: defineAsyncComponent(() => import('../components/blocks/grillas/estructura-organizacional/Editor.vue')),
    EstructuraImagen: defineAsyncComponent(() => import('../components/blocks/grillas/estructura-imagen/Editor.vue')),
    ConsejoDirectivo: defineAsyncComponent(() => import('../components/blocks/grillas/consejo-directivo/Editor.vue')),
    MembershipCertificate: defineAsyncComponent(() => import('../components/blocks/institucional/membership-certificate/Editor.vue')),
    RequirementDocument: defineAsyncComponent(() => import('../components/blocks/institucional/requirement-document/Editor.vue')),
    SecretariaTecnica: defineAsyncComponent(() => import('../components/blocks/grillas/secretaria-tecnica/Editor.vue')),
    CienciaExtremoExtremo: defineAsyncComponent(() => import('../components/blocks/institucional/ciencia-extremo-extremo/Editor.vue')),
    QueHacemosRedInvestigadores: defineAsyncComponent(() => import('../components/blocks/institucional/que-hacemos-red-investigadores/Editor.vue')),
    LineasInvestigacion: defineAsyncComponent(() => import('../components/blocks/institucional/lineas-investigacion/Editor.vue')),
    CtaBannerSection: defineAsyncComponent(() => import('../components/blocks/conversion/cta-banner/Editor.vue')),
    DocumentacionFormal: defineAsyncComponent(() => import('../components/blocks/contenido/documentacion-formal/Editor.vue')),
    EstructuraOferta: defineAsyncComponent(() => import('../components/blocks/contenido/estructura-oferta/Editor.vue')),
    CasoExitoAlianza: defineAsyncComponent(() => import('../components/blocks/contenido/caso-exito-alianza/Editor.vue')),
    ComoColaboramos: defineAsyncComponent(() => import('../components/blocks/institucional/como-colaboramos/Editor.vue')),
    LaboratorioTerritorial: defineAsyncComponent(() => import('../components/blocks/contenido/laboratorio-territorial/Editor.vue')),
    AsambleasGenerales: defineAsyncComponent(() => import('../components/blocks/contenido/asambleas-generales/Editor.vue')),
    DirectorioMiembros: defineAsyncComponent(() => import('../components/blocks/institucional/directorio-miembros/Editor.vue')),
    DirectorioAutoridades: defineAsyncComponent(() => import('../components/blocks/institucional/directorio-autoridades/Editor.vue')),
    AliadosBuscar: defineAsyncComponent(() => import('../components/blocks/institucional/aliados-buscar/Editor.vue')),
    MemoriasCongreso: defineAsyncComponent(() => import('../components/blocks/contenido/memorias-congreso/Editor.vue')),
    GestionConocimiento: defineAsyncComponent(() => import('../components/blocks/contenido/gestion-conocimiento/Editor.vue')),
    InvestigacionesProducidas: defineAsyncComponent(() => import('../components/blocks/contenido/investigaciones-producidas/Editor.vue')),
    AsambleaRectores: defineAsyncComponent(() => import('../components/blocks/institucional/asamblea-rectores/Editor.vue')),
    CooperacionSlider: defineAsyncComponent(() => import('../components/blocks/hero/cooperacion-slider/Editor.vue')),
    NoticiasEventosHub: defineAsyncComponent(() => import('../components/blocks/contenido/noticias-eventos-hub/Editor.vue')),
    BannerInformativo: defineAsyncComponent(() => import('../components/blocks/institucional/banner-informativo/Editor.vue')),
    DynamicContentGrid: defineAsyncComponent(() => import('../components/blocks/contenido/dynamic-content-grid/Editor.vue')),
    AcuerdosScrollHub: defineAsyncComponent(() => import('../components/blocks/contenido/acuerdos-scroll-hub/Editor.vue')),
    SectionTitleDescription: defineAsyncComponent(() => import('../components/blocks/_shared/SectionTitle/Editor.vue')),
    SectionMissionVision: defineAsyncComponent(() => import('../components/blocks/contenido/section-mission-vision/Editor.vue')),
    DynamicGridInfinite: defineAsyncComponent(() => import('../components/blocks/contenido/dynamic-grid-infinite/Editor.vue')),
    DirectorioMiembrosAll: defineAsyncComponent(() => import('../components/blocks/institucional/directorio-miembros-all/Editor.vue')),
    DirectorioAutoridadesAll: defineAsyncComponent(() => import('../components/blocks/institucional/directorio-autoridades-all/Editor.vue')),
    DirectorioEspecialistas: defineAsyncComponent(() => import('../components/blocks/institucional/directorio-especialistas/Editor.vue')),
    HeroWelcome: defineAsyncComponent(() => import('../components/blocks/hero/hero-welcome/Editor.vue'))
    
};

export const resolveEditor = (type: string) => EDITOR_REGISTRY[type] || null;   